---
title: "Project Report"
author: "Eduardo Solano-Salgado"
date: "26/03/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Objective


## Introduction


## Data Source


## Analysis and Discussion


### Univariate Data Analysis

```{r}
library(readxl, logical.return=FALSE)
library(ggplot2, logical.return=FALSE)
library(dplyr, warn.conflicts=FALSE)

WC<- read_xlsx('WorldCup.xlsx')
```

##### World Cup Appearances Analysis
```{r}
Appearance<- pull(WC,7)

hist(Appearance, breaks = 5)
boxplot(Appearance, horizontal=TRUE)

#excluding the value
new_appr <- Appearance[Appearance!=0]
hist(new_appr, breaks = 10, xlab = 'Appearance')
boxplot(new_appr, horizontal = TRUE, xlab ='Appearance')
```
#####GDP Analysis
```{r}
GDP <- pull(WC,5)
is.na(GDP)
hist(GDP)
boxplot(GDP, horizontal = TRUE, na.rm = TRUE)
summary(GDP, na.rm = TRUE)
```
#####Star players Analysis
```{r}
star <- pull(WC,9)
hist(star)
boxplot(star, horizontal = TRUE)
summary(star)

#exclude value 0
new_star <- star[star!=0]
hist(new_star)
boxplot(new_star, horizontal = TRUE)
summary(new_star)
```
### Bivariate Data Analysis

##### Appearances and Number of Star Players
```{r}
z<- lm(Appearances~Stars,data=WC)

ggplot(WC, aes(Stars, Appearances))+geom_point(size=3, shape=16)+
  geom_abline(slope=z$coefficients[2], intercept=z$coefficients[1], color='red')

 cor(WC$Stars, WC$Appearances)
```

##### Gross Domestic Product and Appearances at the World Cup

## Limitations


## Conclusion
